version: '3.7'

services:
  nginx:
    image: {{ env.NGINX_IMAGE }}
    ports:
      - '80:80'

  frontend:
    image: {{ env.FRONTEND_IMAGE }}

  backend:
    image: {{ env.BACKEND_IMAGE }}
    environment:
      - ORIGINS={{ env.FRONTEND_ORIGINS }}
