version: '3.7'

services:
  frontend:
    build:
      context: src/frontend
      dockerfile: Dockerfile

  backend:
    build:
      context: .
      dockerfile: src/backend/Dockerfile
    ports:
      - '8080:80'
