version: '3.7'

services:
  nginx:
    image: {{ env.NGINX_IMAGE }}
    ports:
      - '80:80'
    restart: always
    depends_on:
      - frontend
      - backend

  frontend:
    image: {{ env.FRONTEND_IMAGE }}
    restart: always

  backend:
    image: {{ env.BACKEND_IMAGE }}
    environment:
      ORIGINS: {{ env.FRONTEND_ORIGINS }}
    restart: always
