name: Docker Image CI

on:
  pull_request:
    branches: [ "main" ]

env:
  FRONTEND_IMAGE: ${{ secrets.DOCKER_HUB_USERNAME }}/text-to-image-frontend:latest
  BACKEND_IMAGE: ${{ secrets.DOCKER_HUB_USERNAME }}/text-to-image-api:latest
  NGINX_IMAGE: ${{ secrets.DOCKER_HUB_USERNAME }}/text-to-image-nginx:latest

jobs:

  build-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Login to Dockerhub
      uses: docker/login/action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build Backend
      uses: docker/build-push-action@v3
      with:
        context: src/backend
        file: ./Dockerfile
        push: true
        tags: $BACKEND_IMAGE
    
    - name: Build Frontend
      uses: docker/build-push-action@v3
      with:
        context: src/backend
        file: ./Dockerfile
        push: true
        build-args: |
          server_url: ${{ secrets.API_SERVER_URL }}
        tags: $FRONTEND_IMAGE

    - name: Compose together with Nginx
      uses: docker/build-push-action@v3
      with:
        context: nginx
        file: ./Dockerfile
        push: true
        tags: $NGINX_IMAGE


  update-yc:
    runs-on: ubuntu-latest
    needs: [build-docker]
    steps:

    - name: Login to Yandex Cloud
      id: logic-cr
      uses: yc-actions/yc-cr-login@v1
      with:
        yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
        
    
    - name: Deploy COI VM
      id: deploy-coi
      uses: yc-actions/yc-coi-deploy@v1
      env:
        BACKEND_IMAGE: $BACKEND_IMAGE
        FRONTEND_IMAGE: $FRONTEND_IMAGE
        NGINX_IMAGE: $NGINX_IMAGE
        ORIGINS: ${{ secrets.FRONTEND_ORIGINS }}
      with:
        yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
        folder-id: some-name********
        VM-name: yc-action-demo
        vm-service-account-id: some-account-id*******
        vm-cores: 1
        vm-memory: 512Mb
        vm-core-fraction: 100
        vm-subnet-id: some-subnet-id*********
        user-data-path: what******
        docker-compose-path: './docker-compose.yc.yml'
